#!/bin/sh
RED='\033[0;31m'
BLUE='\033[0;34m'
# Drawing the PACMAN
printf "${BLUE} .--.\n"
printf "${BLUE}/ _.-'${RED} .-.  .-.  .-.\n"
printf "${BLUE}\  '-.${RED} '-'  '-'  '-'\n"
printf "${BLUE} '--'\n"
