#!/bin/sh

battery="/sys/class/power_supply/BAT0"
percent="$(cat "$battery/capacity" 2>&1)"
status="$(cat "$battery/status" 2>&1)"
case "$status" in
	"Full") icon="" ;;
	"Discharging")
		if [ $percent = 100 ]; then
		    icon=""
		elif [ $percent -gt 89 ]; then
		    icon=""
		elif [ $percent -gt 79 ]; then
		    icon=""
		elif [ $percent -gt 69 ]; then
		    icon=""
		elif [ $percent -gt 59 ]; then
		    icon=""
		elif [ $percent -gt 49 ]; then
		    icon=""
		elif [ $percent -gt 39 ]; then
		    icon=""
		elif [ $percent -gt 30 ]; then
		    icon=""
		    $(echo 0 > /tmp/bat.txt)
		elif [ $percent = 30 ]; then
		    icon=""
		    [ $(cat /tmp/bat.txt) = 0 ] && $(dunstify -r 555555  -u normal "$percent % of the battery is remaining") && $(echo 1 > /tmp/bat.txt)
		elif [ $percent -gt 20 ]; then
		    icon=""
		    $(echo 0 > /tmp/bat.txt)
		elif [ $percent = 20 ]; then
		    icon=""
		    [ $(cat /tmp/bat.txt) = 0 ] && $(dunstify -r 555555  -u normal "$percent % of the battery is remaining") && $(echo 1 > /tmp/bat.txt)
	    	elif [ $percent -gt 10 ]; then
		    icon=""
		    $(echo 0 > /tmp/bat.txt)
		elif [ $percent = 10 ]; then
		    icon=""
		    [ $(cat /tmp/bat.txt) = 0 ] && $(dunstify -r 555555  -u critical "$percent % of the battery is remaining") && $(echo 1 > /tmp/bat.txt)
		elif [ $percent -ge 0 ]; then
		    icon=""
		fi ;;

	"Charging")
		if [ $percent = 100 ]; then
			icon=""
		elif [ $percent -gt 89 ]; then
			icon=""
		elif [ $percent -gt 69 ]; then
			icon=""
		elif [ $percent -gt 49 ]; then
			icon=""
		elif [ $percent -gt 39 ]; then
			icon=""
		elif [ $percent -gt 29 ]; then
			icon=""
		elif [ $percent -ge 0 ]; then
			icon=""
		fi ;;

	"Not charging") icon="🛑" ;;
	"Unknown") icon="" ;;
	*) exit 1 ;;
esac
printf "%s %d%%" "$icon" "$percent";
