#!/bin/sh

## If wanna use the pywal color scheme uncomment it
. $HOME/.scripts/dmenu_color
# Get user selection via dmenu from emoji file.
chosen=$(cut -d ';' -f1 ~/.local/share/dmenu/emoji | dmenu \
    -nb $COLOR_BACKGROUND \
    -nf $COLOR_DEFAULT \
    -sf $COLOR_HIGHLIGHT \
    -sb $SELECTED_BACKGROUND \
    -fn 'MononokiNerdFont-20'\
    -i -l 10 -p "Emoji:"| sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
if [ -n "$1" ]; then
	xdotool type "$chosen"
else
	printf "$chosen" | xclip -selection clipboard
	notify-send "'$chosen' copied to clipboard." &
fi
