#!/bin/sh

. $HOME/.scripts/dmenu_base

case "$(echo "Lock\nLogout\nRestart\nShutdown\nSuspend" | dmenu -b $base " ")" in
        Lock) exec lock;;
        Logout) kill -9 -1;;
        Restart) exec systemctl reboot;;
        Shutdown) exec systemctl poweroff;;
        Suspend) exec systemctl suspend;;
esac
