#!/bin/python
import random
loi = ["LINUX", "NET-GATE", "Universities", "MS Thesis I", "MS Thesis II", "NLD", "Me Time"]
ll = len(loi)
order = []
i = 0
print("\n")
#print("\t____________________________________")
print("\t|-----------------------|")
row_format ="{:>15}" *(ll+1)
while i<ll:
    r = random.randint(0,ll-1)
    if loi[r] not in order:
        order.append(loi[r])
        print("\t|  %-13s \t|" % loi[r])
        #print("\t|_______|___________________________|")
        print("\t|-----------------------|")
        i+=1
print("\n")
